2024-02-04 23:06:13 +0000 - dagster - DEBUG - LaborChartETL - c2c5fe40-4654-4cd5-b78c-a957d9b611bf - 445 - LOGS_CAPTURED - Started capturing logs in process (pid: 445).
2024-02-04 23:06:13 +0000 - dagster - DEBUG - LaborChartETL - c2c5fe40-4654-4cd5-b78c-a957d9b611bf - 445 - elempleoExtraction - STEP_START - Started execution of step "elempleoExtraction".
2024-02-04 23:07:13 +0000 - dagster - ERROR - LaborChartETL - c2c5fe40-4654-4cd5-b78c-a957d9b611bf - 445 - elempleoExtraction - STEP_FAILURE - Execution of step "elempleoExtraction" failed.

dagster._core.errors.DagsterExecutionInterruptedError

Stack Trace:
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_plan.py", line 275, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 478, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 160, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 95, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 212, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 181, in _yield_compute_results
    for event in iterate_with_context(
  File "/usr/local/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 465, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/usr/src/app/dataflow.py", line 17, in elempleoExtraction
    offers = webScraperElempleo()
  File "/usr/src/app/etl/extraction/elempleo/webscraper.py", line 106, in webScraperElempleo
    time.sleep(randomSleep())
  File "/usr/local/lib/python3.10/site-packages/dagster/_utils/interrupts.py", line 82, in _new_signal_handler
    raise error_cls()

