2023-11-16 05:13:53 +0000 - dagster - DEBUG - LaborChartETL - ca0684cc-81e8-468d-aed5-79f344d38d1a - 10452 - LOGS_CAPTURED - Started capturing logs in process (pid: 10452).
2023-11-16 05:13:53 +0000 - dagster - DEBUG - LaborChartETL - ca0684cc-81e8-468d-aed5-79f344d38d1a - 10452 - computrabajoExtraction - STEP_START - Started execution of step "computrabajoExtraction".
2023-11-16 05:20:56 +0000 - dagster - INFO - LaborChartETL - ca0684cc-81e8-468d-aed5-79f344d38d1a - computrabajoExtraction - (LABORCHART) Company element from Computrabajo not found
2023-11-16 05:21:38 +0000 - dagster - INFO - LaborChartETL - ca0684cc-81e8-468d-aed5-79f344d38d1a - computrabajoExtraction - (LABORCHART) Company element from Computrabajo not found
2023-11-16 05:21:45 +0000 - dagster - ERROR - LaborChartETL - ca0684cc-81e8-468d-aed5-79f344d38d1a - 10452 - computrabajoExtraction - STEP_FAILURE - Execution of step "computrabajoExtraction" failed.

dagster._core.errors.DagsterExecutionInterruptedError

Stack Trace:
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_plan.py", line 275, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 476, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 159, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 94, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 204, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn):
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 173, in _yield_compute_results
    for event in iterate_with_context(
  File "/usr/local/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 443, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 132, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 126, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/usr/src/app/dataflow.py", line 26, in computrabajoExtraction
    offers = webScraperComputrabajo()
  File "/usr/src/app/etl/extraction/computrabajo/webscraper.py", line 182, in webScraperComputrabajo
    time.sleep(randomSleep())
  File "/usr/local/lib/python3.10/site-packages/dagster/_utils/interrupts.py", line 82, in _new_signal_handler
    raise error_cls()

